FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        cmake \
        ninja-build \
        python3 \
        python3-pip \
        git \
        wget \
        curl \
        pkg-config \
        libpthread-stubs0-dev \
        protobuf-compiler \
        libprotobuf-dev \
        libgtest-dev \
        libgmock-dev \
        lcov \
        gcovr \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /vnet
COPY . /vnet

RUN mkdir -p build
WORKDIR /vnet/build
RUN cmake -B . -S .. -GNinja -DENABLE_COVERAGE=ON -DBUILD_TESTS=ON && ninja

ENTRYPOINT ["ctest", "--output-on-failure", "-j4"]
